version: "3.7"

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
  unpub:
    container_name: unpub
    build:
      context: ./
    restart: always
    volumes:
      - .:/app
    ports:
      - 4000:4000
    links:
        - mongodb
    depends_on:
        - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
