name: lint
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    # container:
    #   image: google/dart:latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: '3.7.9'
          architecture: x64
      - run: cd unpub && dart pub get && dart analyze
      - run: dart format --set-exit-if-changed **/*.dart
