name: Push on main
on:
  workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0
    
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v2
    
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
        
          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v2
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ secrets.AWS_REGION }}
    
          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v1
    
          - name: Build
            run: dart pub get

        #   - name: Calculate timestamp tag
        #     id: timestamptagcalc
        #     env:
        #       BUILD_INFO_FILE: 'server/build/resources/main/META-INF/build-info.properties'
        #     run: |
        #       # Create tag. Note this doesn't completely follow semver because docker tags do not take a + sign
        #       ts=$([ -e $BUILD_INFO_FILE ] && echo ${{steps.login-ecr.outputs.registry}}/${{github.repository}}:timestamp-$(grep "build.time=" $BUILD_INFO_FILE | cut -d"=" -f2 | tr -d '\\:.-') || echo "");
        #       echo $ts
        #       echo "tag=$ts" >> $GITHUB_OUTPUT
    
          - name: Build and push images to ECR
            uses: docker/build-push-action@v4
            with:
              context: server
              platforms: linux/amd64,linux/arm64
              push: true
              tags: |
                ${{steps.login-ecr.outputs.registry}}/${{github.repository}}:latest
                ${{steps.login-ecr.outputs.registry}}/${{github.repository}}:gitcommit-${{ github.sha }}
                ${{steps.login-ecr.outputs.registry}}/${{github.repository}}:gitrun-${{ github.run_id }}
            # ${{ steps.timestamptagcalc.outputs.tag }}
